import { FC } from 'react'

type IHomeContent = {
    title?: string
    description?: string
}
export const HomeMetaData: IHomeContent = {
    title: 'Claudio Lau',
    description: 'Generated by create next app',
}

export const HomeContent: FC<typeof HomeMetaData> = ({
    title = `${HomeMetaData.title}`,
    description = `${HomeMetaData.description}`,
}) => {
    return (
        <>
            <div>{title}</div>
            <div>{description}</div>
        </>
    )
}
